
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 9092

security:
  user:
    name: user
    password: 1234


profiles:
  include: security


mybatis:
 mapper-locations: mapper/**/*.xml

configuration:
     map-underscore-to-camel-case: true
